version: "3"

services:
  db:
    image: postgres
    container_name: PISTE_DB
    restart: unless-stopped
    environment:
      - POSTGRES_DB=PisteDB
      - POSTGRES_USER=puma_prod
      - POSTGRES_PASSWORD=puma_prod
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5167:5432"
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: piste_prod:latest
    restart: unless-stopped
    container_name: PISTE_APP
    ports:
      - "8167:8167"
    volumes:
      - ./piste:/piste

    command: >
      sh -c " python manage.py makemigrations &&
              python manage.py migrate &&
              python manage.py runserver 0.0.0.0:8167"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_NAME=PisteDB
      - DB_USER=puma_prod
      - DB_PASS=puma_prod
      - DB_PORT=5432
  cron:
    build: 
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    image: piste_cron
    container_name: PISTE_CRON
    depends_on:
    - db
    environment:
      - DB_HOST=db
      - DB_NAME=PisteDB
      - DB_USER=puma_prod
      - DB_PASS=puma_prod
      - DB_PORT=5432
    command: >
      sh -c " python manage.py crontab add &&
              crond -f"
volumes:
  db_data:
networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.76.0/24